name: Build Docker Images

on:
  pull_request:
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - "*.md"
      - "binder/**"
      - "docs/**"
      - "examples/**"
      - ".pre-commit-config.yaml"
  push:
    branches:
      - master
      - main
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - "*.md"
      - "binder/**"
      - "docs/**"
      - "examples/**"
      - ".pre-commit-config.yaml"

jobs:
  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: >
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.pull_request.title, 'ci skip')
    steps:
      - name: Should we push this image to a public registry?
        run: |
          if [ "${{ startsWith(github.ref, 'refs/tags/') || (github.ref == 'refs/heads/main') }}" = "true" ]; then
              # Empty => Docker Hub
              echo "REGISTRY=" >> $GITHUB_ENV
          else
              echo "REGISTRY=localhost:5000/" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v2

      # Setup docker to build for multiple platforms, see:
      # https://github.com/docker/build-push-action/tree/v2.4.0#usage
      # https://github.com/docker/build-push-action/blob/v2.4.0/docs/advanced/multi-platform.md

      - name: Set up QEMU (for docker buildx)
        uses: docker/setup-qemu-action@25f0500ff22e406f7191a2a8ba8cda16901ca018 # associated tag: v1.0.2

      - name: Set up Docker Buildx (for multi-arch builds)
        uses: docker/setup-buildx-action@2a4b53665e15ce7d7049afb11ff1f70ff1610609 # associated tag: v1.1.2
        with:
          # Allows pushing to registry on localhost:5000
          driver-opts: network=host
      - name: Clone Main Repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make -C main dev-env
      - name: Build Docker Images
        run: make -C main build-test-all
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain
      - name: Clone Wiki
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: Run Post-Build Hooks
        run: make -C main hook-all
      - name: Push Wiki to GitHub
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@5dd17c3b53a58c1cb5eaab903826abe94765ccd6 # dependabot updates to latest release
        with:
          commit_message: "[ci skip] Automated publish for ${{github.sha}}"
          repository: wiki/
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # dependabot updates to latest release
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
